#!/usr/bin/env bash
# Regenerates the two pasteable SQL bundles from supabase/migrations + seed.
#
#   supabase/schema.sql    migrations only  -> PRODUCTION
#   supabase/bootstrap.sql migrations + seed -> DEV ONLY (creates test accounts)
set -euo pipefail
cd "$(dirname "$0")/.."

emit_migrations() {
  for f in $(ls supabase/migrations/*.sql | sort); do
    printf '\n-- ============================================================================\n'
    printf -- '-- %s\n' "$f"
    printf -- '-- ============================================================================\n\n'
    cat "$f"
  done
}

{
  cat <<'HDR'
-- Stub — schema only (migrations, no seed data).
--
-- Paste this into the SQL editor of a PRODUCTION Supabase project. It creates
-- every table, policy, function and trigger, and NO user accounts.
--
-- Do NOT also run supabase/seed.sql against production: that creates five test
-- accounts whose password is committed to this public repo.
--
-- Generated by scripts/build-bootstrap.sh — do not edit by hand.
HDR
  emit_migrations
} > supabase/schema.sql

{
  cat <<'HDR'
-- Stub — full bootstrap: migrations + seed data.
--
-- DEV AND TEST ONLY. The seed creates five accounts with the password
-- `stubdemo123`, which is committed to this public repo. Never run this against
-- a database anyone else can reach — use supabase/schema.sql there instead.
--
-- Generated by scripts/build-bootstrap.sh — do not edit by hand.
HDR
  emit_migrations
  printf '\n-- ============================================================================\n'
  printf -- '-- supabase/seed.sql\n'
  printf -- '-- ============================================================================\n\n'
  cat supabase/seed.sql
} > supabase/bootstrap.sql

echo "wrote supabase/schema.sql    ($(wc -l < supabase/schema.sql | tr -d ' ') lines, no seed)"
echo "wrote supabase/bootstrap.sql ($(wc -l < supabase/bootstrap.sql | tr -d ' ') lines, with seed)"
