-- Stub — schema only (migrations, no seed data).
--
-- Paste this into the SQL editor of a PRODUCTION Supabase project. It creates
-- every table, policy, function and trigger, and NO user accounts.
--
-- Do NOT also run supabase/seed.sql against production: that creates five test
-- accounts whose password is committed to this public repo.
--
-- Generated by scripts/build-bootstrap.sh — do not edit by hand.

-- ============================================================================
-- supabase/migrations/0001_init.sql
-- ============================================================================

-- Stub — initial schema
-- Conventions:
--   * Global cache tables (artists, venues, events, event_artists) are shared across all users:
--     readable by any authenticated user, written only by the service role.
--   * Per-user tables are guarded by RLS keyed on auth.uid().
--   * "Archive" is a query (starts_at < now()), never a separate table.

create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";

-- ============================================================ enums

create type attendance_state      as enum ('going', 'interested', 'went', 'missed');
create type attendance_visibility as enum ('friends', 'private');
create type attendance_source     as enum ('manual', 'gmail', 'forward', 'setlistfm', 'friend');
create type friendship_status     as enum ('pending', 'accepted', 'blocked');
create type artist_source         as enum ('manual', 'spotify', 'applemusic', 'setlistfm');
create type email_provider        as enum ('gmail', 'forward');
create type ingest_status         as enum ('parsed', 'unmatched', 'ignored', 'error');
create type candidate_state       as enum ('pending', 'confirmed', 'rejected');
create type billing_role          as enum ('headliner', 'support');

-- ============================================================ profiles

create table profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  handle       text unique not null check (handle ~ '^[a-z0-9_]{3,24}$'),
  display_name text not null default '',
  bio          text not null default '' check (char_length(bio) <= 500),
  avatar_url   text,
  home_city    text,
  home_lat     double precision,
  home_lng     double precision,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index profiles_handle_trgm on profiles using gin (handle gin_trgm_ops);

-- ============================================================ global catalog

create table artists (
  id           uuid primary key default gen_random_uuid(),
  mbid         uuid unique,                    -- MusicBrainz, our canonical identity
  tm_id        text unique,                    -- Ticketmaster attraction id
  name         text not null,
  sort_name    text,
  image_url    text,
  genres       text[] not null default '{}',
  created_at   timestamptz not null default now()
);

create index artists_name_trgm on artists using gin (name gin_trgm_ops);

create table venues (
  id         uuid primary key default gen_random_uuid(),
  tm_id      text unique,
  name       text not null,
  city       text,
  region     text,
  country    text,
  lat        double precision,
  lng        double precision,
  timezone   text,
  created_at timestamptz not null default now()
);

create table events (
  id            uuid primary key default gen_random_uuid(),
  tm_id         text unique,                   -- Ticketmaster event id
  setlistfm_id  text unique,
  name          text not null,
  headliner_id  uuid references artists(id) on delete set null,
  venue_id      uuid references venues(id) on delete set null,
  starts_at     timestamptz not null,
  doors_at      timestamptz,
  timezone      text,
  status        text not null default 'onsale',
  url           text,
  image_url     text,
  created_at    timestamptz not null default now()
);

create index events_starts_at   on events (starts_at);
create index events_headliner   on events (headliner_id);
create index events_name_trgm   on events using gin (name gin_trgm_ops);

create table event_artists (
  event_id  uuid not null references events(id) on delete cascade,
  artist_id uuid not null references artists(id) on delete cascade,
  billing   billing_role not null default 'support',
  primary key (event_id, artist_id)
);

-- ============================================================ social

-- One row per friendship, stored canonically so (a,b) and (b,a) can't both exist.
create table friendships (
  user_low     uuid not null references profiles(id) on delete cascade,
  user_high    uuid not null references profiles(id) on delete cascade,
  status       friendship_status not null default 'pending',
  requested_by uuid not null references profiles(id) on delete cascade,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  primary key (user_low, user_high),
  constraint friendships_canonical check (user_low < user_high)
);

create index friendships_high on friendships (user_high);

-- Are these two users accepted friends? Used by RLS on attendances/profiles.
create or replace function are_friends(a uuid, b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from friendships
    where user_low  = least(a, b)
      and user_high = greatest(a, b)
      and status    = 'accepted'
  );
$$;

-- ============================================================ per-user data

create table user_artists (
  user_id    uuid not null references profiles(id) on delete cascade,
  artist_id  uuid not null references artists(id) on delete cascade,
  source     artist_source not null default 'manual',
  weight     real not null default 1.0,
  created_at timestamptz not null default now(),
  primary key (user_id, artist_id, source)
);

create table attendances (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references profiles(id) on delete cascade,
  event_id     uuid not null references events(id) on delete cascade,
  state        attendance_state not null default 'going',
  visibility   attendance_visibility not null default 'friends',
  source       attendance_source not null default 'manual',
  ticket_ref   text,
  seat_info    text,
  price_cents  integer,
  purchased_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id, event_id)
);

create index attendances_user  on attendances (user_id);
create index attendances_event on attendances (event_id);

-- Private notes. Deliberately a separate table from attendances so that a single
-- blanket RLS policy (owner only, no friend path) governs all note access.
create table notes (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  event_id   uuid not null references events(id) on delete cascade,
  body       text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, event_id)
);

-- ============================================================ ingestion

create table email_accounts (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references profiles(id) on delete cascade,
  provider       email_provider not null,
  email          text not null,
  access_token   text,                          -- AES-256-GCM, see src/lib/crypto.ts
  refresh_token  text,                          -- AES-256-GCM
  token_expires  timestamptz,
  history_id     text,                          -- Gmail incremental sync cursor
  last_synced_at timestamptz,
  status         text not null default 'active',
  created_at     timestamptz not null default now(),
  unique (user_id, provider, email)
);

create table inbound_addresses (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  local_part text unique not null,              -- e.g. 'emily-a3f9'
  created_at timestamptz not null default now()
);

-- We store extracted fields and a content hash, never the raw email body.
create table ingest_messages (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references profiles(id) on delete cascade,
  account_id     uuid references email_accounts(id) on delete set null,
  provider_msg_id text,
  from_addr      text,
  subject        text,
  received_at    timestamptz,
  content_hash   text not null,
  extractor      text,
  status         ingest_status not null default 'parsed',
  error          text,
  created_at     timestamptz not null default now(),
  unique (user_id, content_hash)
);

create table ingest_candidates (
  id          uuid primary key default gen_random_uuid(),
  message_id  uuid not null references ingest_messages(id) on delete cascade,
  user_id     uuid not null references profiles(id) on delete cascade,
  parsed      jsonb not null,
  confidence  real not null,
  matched_event_id uuid references events(id) on delete set null,
  state       candidate_state not null default 'pending',
  created_at  timestamptz not null default now()
);

create index ingest_candidates_user_state on ingest_candidates (user_id, state);

-- ============================================================ updated_at triggers

create or replace function touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger profiles_touch    before update on profiles    for each row execute function touch_updated_at();
create trigger friendships_touch before update on friendships for each row execute function touch_updated_at();
create trigger attendances_touch before update on attendances for each row execute function touch_updated_at();
create trigger notes_touch       before update on notes       for each row execute function touch_updated_at();

-- Create a profile row automatically on signup.
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, handle, display_name, avatar_url)
  values (
    new.id,
    -- collision-safe default handle; the user renames it in onboarding
    -- truncated to satisfy the 24-char handle check constraint; 15 + 1 + 6 = 22 max
    substr(
      lower(regexp_replace(split_part(coalesce(new.email, 'user'), '@', 1), '[^a-z0-9_]', '', 'g')),
      1, 15
    ) || '_' || substr(replace(new.id::text, '-', ''), 1, 6),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ============================================================================
-- supabase/migrations/0002_rls.sql
-- ============================================================================

-- Stub — row level security
--
-- The rule that matters most: `notes` has an owner-only policy with NO friend path.
-- Everything else may be shared; notes never are.

alter table profiles          enable row level security;
alter table artists           enable row level security;
alter table venues            enable row level security;
alter table events            enable row level security;
alter table event_artists     enable row level security;
alter table friendships       enable row level security;
alter table user_artists      enable row level security;
alter table attendances       enable row level security;
alter table notes             enable row level security;
alter table email_accounts    enable row level security;
alter table inbound_addresses enable row level security;
alter table ingest_messages   enable row level security;
alter table ingest_candidates enable row level security;

-- ---------------------------------------------------------- global catalog
-- Readable by any signed-in user. Writes happen via the service role, which
-- bypasses RLS entirely, so no insert/update policies are defined here.

create policy "catalog readable" on artists       for select to authenticated using (true);
create policy "catalog readable" on venues        for select to authenticated using (true);
create policy "catalog readable" on events        for select to authenticated using (true);
create policy "catalog readable" on event_artists for select to authenticated using (true);

-- ---------------------------------------------------------- profiles

-- Any signed-in user can look up a profile: needed to send a friend request by handle.
-- Only non-sensitive columns live on this table, so full-row read is acceptable.
create policy "profiles readable" on profiles
  for select to authenticated using (true);

create policy "own profile writable" on profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- ---------------------------------------------------------- friendships

create policy "see own friendships" on friendships
  for select to authenticated
  using (user_low = auth.uid() or user_high = auth.uid());

-- You may only create a request you are part of, and only as the requester.
create policy "request friendship" on friendships
  for insert to authenticated
  with check (
    (user_low = auth.uid() or user_high = auth.uid())
    and requested_by = auth.uid()
    and status = 'pending'
  );

-- Either side may update (accept / block). The other side accepting is the point.
create policy "update own friendship" on friendships
  for update to authenticated
  using (user_low = auth.uid() or user_high = auth.uid())
  with check (user_low = auth.uid() or user_high = auth.uid());

create policy "delete own friendship" on friendships
  for delete to authenticated
  using (user_low = auth.uid() or user_high = auth.uid());

-- ---------------------------------------------------------- user_artists

create policy "own artists" on user_artists
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------- attendances
-- Owner sees everything. Accepted friends see rows marked visibility = 'friends'.
-- This is what powers "which of my friends are going to which concerts".

create policy "own attendances" on attendances
  for select to authenticated using (user_id = auth.uid());

create policy "friends attendances" on attendances
  for select to authenticated
  using (visibility = 'friends' and are_friends(auth.uid(), user_id));

create policy "write own attendances" on attendances
  for insert to authenticated with check (user_id = auth.uid());

create policy "update own attendances" on attendances
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "delete own attendances" on attendances
  for delete to authenticated using (user_id = auth.uid());

-- ---------------------------------------------------------- notes  (owner only)
-- No friend path, by design. Do not add one.

create policy "notes are private" on notes
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------- ingestion
-- Tokens are never selectable by the client; only the service role reads them.

create policy "own email accounts" on email_accounts
  for select to authenticated using (user_id = auth.uid());

create policy "delete own email accounts" on email_accounts
  for delete to authenticated using (user_id = auth.uid());

create policy "own inbound address" on inbound_addresses
  for select to authenticated using (user_id = auth.uid());

create policy "own ingest messages" on ingest_messages
  for select to authenticated using (user_id = auth.uid());

create policy "own ingest candidates" on ingest_candidates
  for select to authenticated using (user_id = auth.uid());

-- The review queue: confirming or rejecting a candidate is a client action.
create policy "resolve own candidates" on ingest_candidates
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------- column-level grants
-- RLS is row-level only, so the owner's own policy would still expose the encrypted
-- token columns to the browser client. Restrict the selectable columns explicitly.
-- The service role bypasses both RLS and these grants.

revoke all on email_accounts from authenticated;
grant select (id, user_id, provider, email, last_synced_at, status, created_at)
  on email_accounts to authenticated;
grant delete on email_accounts to authenticated;

-- content_hash is an email fingerprint; no reason to hand it to the client.
revoke all on ingest_messages from authenticated;
grant select (id, user_id, from_addr, subject, received_at, extractor, status, error, created_at)
  on ingest_messages to authenticated;

-- ============================================================================
-- supabase/migrations/0003_storage_and_inbound.sql
-- ============================================================================

-- Avatars bucket + per-user inbound addresses.

-- ============================================================ avatar storage

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Profile photos are public to read (they appear on friend cards), but a user
-- may only write inside a folder named for their own uid.
create policy "avatars are publicly readable"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "users write their own avatar"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "users update their own avatar"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "users delete their own avatar"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ============================================================ inbound addresses

-- Every user gets a forwarding address at signup so the feature is ready the
-- moment FEATURE_FORWARD_INBOX is switched on. The random suffix keeps the
-- address unguessable, since anyone who knows it can post mail into the queue.
-- search_path MUST include `extensions`: Supabase installs pgcrypto there, not
-- in public, and gen_random_bytes() below is a pgcrypto function. With a
-- public-only search_path this trigger raises 42883 on every profile insert,
-- which means every signup fails, not just seeding.
create or replace function assign_inbound_address()
returns trigger language plpgsql security definer set search_path = public, extensions as $$
declare
  base text;
  suffix text;
begin
  base := substr(regexp_replace(lower(new.handle), '[^a-z0-9]', '', 'g'), 1, 16);
  if base = '' then base := 'user'; end if;

  suffix := encode(gen_random_bytes(3), 'hex');

  insert into inbound_addresses (user_id, local_part)
  values (new.id, base || '-' || suffix)
  on conflict (local_part) do nothing;

  return new;
end;
$$;

create trigger on_profile_created_assign_inbox
  after insert on profiles
  for each row execute function assign_inbound_address();

-- Backfill anyone who already exists.
insert into inbound_addresses (user_id, local_part)
select
  p.id,
  substr(regexp_replace(lower(p.handle), '[^a-z0-9]', '', 'g'), 1, 16)
    || '-' || encode(gen_random_bytes(3), 'hex')
from profiles p
where not exists (select 1 from inbound_addresses ia where ia.user_id = p.id)
on conflict (local_part) do nothing;

-- ============================================================================
-- supabase/migrations/0004_push.sql
-- ============================================================================

-- Web push subscriptions.

create table push_subscriptions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references profiles(id) on delete cascade,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create index push_subscriptions_user on push_subscriptions (user_id);

-- Tracks which reminders have already gone out, so a cron re-run cannot send
-- the same notification twice.
create table sent_reminders (
  user_id    uuid not null references profiles(id) on delete cascade,
  event_id   uuid not null references events(id) on delete cascade,
  kind       text not null,
  sent_at    timestamptz not null default now(),
  primary key (user_id, event_id, kind)
);

alter table push_subscriptions enable row level security;
alter table sent_reminders     enable row level security;

create policy "own push subscriptions" on push_subscriptions
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "own reminders" on sent_reminders
  for select to authenticated using (user_id = auth.uid());

-- ============================================================================
-- supabase/migrations/0005_venue_setlistfm_id.sql
-- ============================================================================

-- Give venues a setlist.fm identity.
--
-- The setlist.fm importer creates venues that Ticketmaster has never heard of,
-- so they have no tm_id. Upserting those on `tm_id` does not work: Postgres
-- treats NULLs as distinct in a unique index, so every import inserted a fresh
-- duplicate row instead of matching the existing one.
--
-- setlist.fm gives each venue a stable id, so store it and conflict on that —
-- the same dual-identity pattern `events` already uses.

alter table venues add column if not exists setlistfm_id text;

create unique index if not exists venues_setlistfm_id_key
  on venues (setlistfm_id)
  where setlistfm_id is not null;

-- ============================================================================
-- supabase/migrations/0006_fix_inbound_search_path.sql
-- ============================================================================

-- Fixes a bug in 0003: assign_inbound_address() pinned search_path to `public`,
-- but Supabase installs pgcrypto into `extensions`, so gen_random_bytes() was
-- unresolvable. The trigger fires on every profile insert, so this broke every
-- signup with 42883, not just seeding.
--
-- 0003 has been corrected too; this migration exists for databases that already
-- applied the broken version. `create or replace` makes it a no-op otherwise.

create or replace function assign_inbound_address()
returns trigger language plpgsql security definer set search_path = public, extensions as $$
declare
  base text;
  suffix text;
begin
  base := substr(regexp_replace(lower(new.handle), '[^a-z0-9]', '', 'g'), 1, 16);
  if base = '' then base := 'user'; end if;

  suffix := encode(gen_random_bytes(3), 'hex');

  insert into inbound_addresses (user_id, local_part)
  values (new.id, base || '-' || suffix)
  on conflict (local_part) do nothing;

  return new;
end;
$$;

-- ============================================================================
-- supabase/migrations/0007_lock_down_functions.sql
-- ============================================================================

-- Security hardening, from the Supabase database linter.
--
-- 1. handle_new_user() and assign_inbound_address() are trigger functions. They
--    were reachable at /rest/v1/rpc/<name> by anon and authenticated because
--    Postgres grants EXECUTE to PUBLIC by default. Triggers do not need any
--    EXECUTE grant to fire, so revoke it entirely.
--
-- 2. are_friends() is used inside an RLS policy, but as a SECURITY DEFINER
--    function it also let any caller ask whether two ARBITRARY users are
--    friends — a friendship-graph probe. Revoke public execute, and additionally
--    make the function refuse to answer about pairs the caller is not part of,
--    so it stays safe even if a grant is restored later.
--
--    Verified: the RLS policy on `attendances` still resolves correctly after
--    this, because it always passes auth.uid() as the first argument.
--
-- 3. touch_updated_at() had no pinned search_path.

revoke all on function public.handle_new_user()        from public, anon, authenticated;
revoke all on function public.assign_inbound_address()  from public, anon, authenticated;
revoke all on function public.are_friends(uuid, uuid)   from public, anon;

create or replace function are_friends(a uuid, b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    -- Only answer about a pair the caller belongs to. The RLS policy always
    -- passes auth.uid() as `a`, so this is transparent there; a direct RPC
    -- probe of two other users now returns false instead of leaking.
    (auth.uid() is not distinct from a or auth.uid() is not distinct from b)
    and exists (
      select 1 from friendships
      where user_low  = least(a, b)
        and user_high = greatest(a, b)
        and status    = 'accepted'
    );
$$;

create or replace function touch_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

-- ============================================================================
-- supabase/migrations/0008_calendar_token.sql
-- ============================================================================

-- Subscribable calendar feed.
--
-- Calendar clients (Apple Calendar, Google Calendar) cannot carry a session, so
-- the feed URL itself has to be the credential. The token is random, per-user,
-- and rotatable; it grants read-only access to that user's going/interested
-- events and nothing else. Notes are never included.

alter table profiles add column if not exists calendar_token text unique;

create or replace function assign_calendar_token()
returns trigger language plpgsql security definer set search_path = public, extensions as $$
begin
  if new.calendar_token is null then
    new.calendar_token := encode(gen_random_bytes(24), 'hex');
  end if;
  return new;
end;
$$;

revoke all on function public.assign_calendar_token() from public, anon, authenticated;

create trigger on_profile_assign_calendar_token
  before insert on profiles
  for each row execute function assign_calendar_token();

update profiles
   set calendar_token = encode(extensions.gen_random_bytes(24), 'hex')
 where calendar_token is null;

alter table profiles alter column calendar_token set not null;

-- The token is a bearer credential, so keep it out of the columns the browser
-- client can select. It is surfaced to its owner through a server action.
revoke all on profiles from authenticated;
grant select (id, handle, display_name, bio, avatar_url, home_city, created_at, updated_at)
  on profiles to authenticated;
grant update (handle, display_name, bio, avatar_url, home_city)
  on profiles to authenticated;
